package com.example.nammasantheledger

import android.app.Application
import androidx.lifecycle.*
import com.example.nammasantheledger.data.AppDatabase
import com.example.nammasantheledger.data.Customer
import com.example.nammasantheledger.data.CustomerBalance
import com.example.nammasantheledger.data.Transaction
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.*

class GramaViewModel(application: Application) : AndroidViewModel(application) {
    private val dao = AppDatabase.getDatabase(application).transactionDao()

    val customerBalances: LiveData<List<CustomerBalance>> = combine(
        dao.getCustomerBalances(),
        dao.getAllTransactions()
    ) { balances, transactions ->
        balances.map { balance ->
            balance.apply {
                this.transactions = transactions.filter { it.customerName == balance.customerName }
            }
        }.sortedByDescending { it.balance } // 1. Customer Priority: Highest due first
    }.asLiveData()

    val totalNetDue: LiveData<Double> = customerBalances.map { balances ->
        balances.sumOf { it.balance }
    }

    fun addTransaction(name: String, amount: Double, type: String, phone: String? = null) {
        viewModelScope.launch(Dispatchers.IO) {
            // Ensure customer exists
            val existingCustomer = dao.getCustomerByName(name)
            if (existingCustomer == null) {
                dao.insertCustomer(Customer(name = name, phoneNumber = phone))
            }
            
            // Add transaction
            val transaction = Transaction(
                customerName = name,
                amount = amount,
                type = type,
                timestamp = System.currentTimeMillis()
            )
            dao.insertTransaction(transaction)
        }
    }

    fun generateDailyReport(): String {
        val balances = customerBalances.value ?: emptyList()
        val total = totalNetDue.value ?: 0.0
        val date = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault()).format(Date())
        
        return buildString {
            append("--- Gramakhata Daily Report ---\n")
            append("Date: $date\n\n")
            if (balances.isEmpty()) {
                append("No outstanding dues.\n")
            } else {
                balances.forEach {
                    append("${it.customerName}: ₹${String.format("%.2f", it.balance)}\n")
                }
            }
            append("\nTotal Outstanding: ₹${String.format("%.2f", total)}")
            append("\n\nGenerated by Gramakhata")
        }
    }
}
